### ISSUE TITLE
Since today TimeManager not working anymore

### ISSUE THREAD

**Issue by ilfarpro** [ArVdC/TimeManager#14]
First I get the same issue with version 1.5.1 which was installed previously. Then I updated to the latest version 1.6.0 but nothing changed.
![image](https://user-images.githubusercontent.com/16963651/145193650-9f01e64a-8412-4759-b27c-e899e24eec45.png)

**Comment by ArVdC** [comment]
Hi,
The plugin seems to be unable to determine the current version of your lang.yml file.
I'm not sure I can guess the exact cause of the problem, but you should try erasing (or renaming) the file.
Otherwise, it may be possible to correct this setting manually in Notepad.

**Comment by ilfarpro** [comment]
Thanks. It solved problem. I just completely reinstalled and reconfigured plugin. Here's the next issue... I'm sorry I might missed something but plugin reseting config file to default values on each server launch. I just want to set day speed 0.5 and night 1.5.
Do I need to connect plugin to MySQL DB to make it work as intended?
![image](https://user-images.githubusercontent.com/16963651/145530923-f6b5eb02-9e3f-404b-b4d7-53654751ed64.png)

**Comment by ArVdC** [comment]
The SQL database is only useful if you are synchronizing worlds on different servers.
The worlds settings are in the config.yml file.
There does not seem to be a reason for this reset.
Try to save the file when the server is off or use the commands when it is on.

**Comment by ilfarpro** [comment]
I don't know what was the problem but since migration to 1.18.1 everything works just fine. And error messages were created by corrupted configs. This issue can be closed now. Thanks.
