### ISSUE TITLE
days don't go on

### ISSUE THREAD

**Issue by FedericoLupoli** [ArVdC/TimeManager#15]
when the time reaches that to trigger the new day, the day remains the same

**Comment by ArVdC** [comment]
Hi, can you give me some more informations ? (your server version, Timemanager config file content, ...)

**Comment by FedericoLupoli** [comment]
initialTick:
  useMySql: 'false'
  resetOnStartup: 'false'
  initialTickNb: 1114416
debugMode: 'false'
mySql:
  dbPrefix: ''
  username: root
  password: SIB1RRA2vMIwPyFbCkRu$oRt3
  host: localhost
  port: '3306'
  ssl: 'false'
  database: timemanager
  table: refTick
refreshRate: 2
wakeUpTick: 0
newDayAt: 00:00
updateMsgSrc: None
placeholders:
  PlaceholderAPI: 'true'
  MVdWPlaceholderAPI: 'false'
worldsList:
  world:
    start: 808
    daySpeed: 1.0
    nightSpeed: 1.0
    sleep: 'false'
    sync: 'true'
  world_the_end:
    start: 0
    daySpeed: 1.0
    nightSpeed: 1.0
    sleep: 'true'
    sync: 'false'
version: 1.6.1




Server version: 1.16.5

**Comment by ArVdC** [comment]
By saying "the day remains the same", what exactly do you mean ?
Which placeholder are you using ? _{tm_currentday}_, _{tm_elapseddays}_, ...
Are you using the /now command or a scoreboard plugin or something ?

**Comment by FedericoLupoli** [comment]
fixed
