### ISSUE TITLE
Real time minecraft world 

### ISSUE THREAD

**Issue by HelloALe123** [ArVdC/TimeManager#18]
I just started building my own self hosted server and i needed a way to sincronize my local time to the server time but i can't do it because when the server goes off and comes on again some time later the time starts back from when it stopped or it just starts back from 6 am is there any way i can make it sincronized with my local time or do i need a differnt plugin?
I am not really good at this so please help me if you can.

**Comment by ArVdC** [comment]
I think this is the good plugin for you.
If you want your world not to reset to 6am every time the server restarts, just go to the config file and set 'resetOnStartup' to 'false'.
If you want a world to have the exact same time as your real location, set that world's timer to a 'speed' of '24' and use the 'start' value to set the desired time offset.

**Comment by HelloALe123** [comment]
> I think this is the good plugin for you. If you want your world not to reset to 6am every time the server restarts, just go to the config file and set 'resetOnStartup' to 'true'. If you want a world to have the exact same time as your real location, set that world's timer to a 'speed' of '24' and use the 'start' value to set the desired time offset.

my problem is that i don't know when i am going to close it or restart it so i am going to end up with the world at a different time every time i restart it

**Comment by ArVdC** [comment]
The 'resetOnStartup' allows you to keep continuity over time when your server restarts immediately after being stopped. But no function of this plugin allows memorizing the world time when stopping to resume the game exactly at the same time. Sorry.

**Comment by ArVdC** [comment]
I'm working on it, watch for the upcoming release of update 1.7.

**Comment by ArVdC** [comment]
Ok, done : [https://dev.bukkit.org/projects/mc-timemanager/files/4366832/download](https://dev.bukkit.org/projects/mc-timemanager/files/4366832/download)
Use "firstStartTime: previous" to do what you asked here above.
