### ISSUE TITLE
All TM configs not saving.

### ISSUE THREAD

**Issue by Brithim** [ArVdC/TimeManager#19]
Hello, I've been trying to chnage the lang.yml, config.yml & cmds.yml. All of the configs after the server restarts are reset. Running Purpur 1.19.3(fork of paper). Can / will provide more detail if needed

**Comment by ArVdC** [comment]
Hello, I tried the plugin with Purpur but it works quite normally.
Are the yml files reset when the server is stopped or restarted ?

**Comment by Brithim** [comment]
Only when I go to restart the server they will reset. I now start shutting my server down to edit the configs which seems to work. Also, anytime I go to do /tm resync there's an internal error, not sure if you want a new issue opened for this. Thanks for the quick response

**Comment by ArVdC** [comment]
There are three correct ways to edit yml files :
With the commands, in game or in the console ;
By modifying these files when the server is off ;
By modifying these files while the server is running and using the /tm reload command afterwards.

I tried /tm resync but no error appears. Could you provide me with a copy of the .log file ?

**Comment by Brithim** [comment]
It seems resetting all configs (new server) seemed to fix the issue, hasn't happened since. Also, are there plans to add in weather control in the future so that when I extend the days to about 40 mins it's not raining every 10-15 mins? thanks
