### ISSUE TITLE
Request - porting to Fabric

### ISSUE THREAD

**Issue by SleepyCatten** [ArVdC/TimeManager#20]
Hi!

There is currently no Fabric mod that works like TimeManager. Is there any chance that you would consider porting it to Fabric? 🥺👉👈

Kind regards
Evie

**Comment by ArVdC** [comment]
Hi, I did not know Fabric. I looked on their site how to create a mod but I don't quite understand how to transpose my code.
Maybe you could try this mod first: https://www.curseforge.com/minecraft/mc-mods/cardboard? This should make it possible to use spigot plugins with Fabric.
Please let me know if it works.
