### ISSUE TITLE
Requests for cmds, etc.

### ISSUE THREAD

**Issue by sorandno** [ArVdC/TimeManager#22]
Please make it possible to set a wait time between commands in the description of cmds.yml.

Wouldn't it be possible to set a delay between executing multiple commands?

Also, I want you to officially support versions 1.19.4 and 1.20 and later.

**Comment by ArVdC** [comment]
Good idea, I'll try to do this soon.
I've already tested with the latest mc version and it seems 100% compatible.
Just wait a bit for the next release.

**Comment by sorandno** [comment]
looking forward to it.
