### ISSUE TITLE
Time cycle stopping at specific time of day

### ISSUE THREAD

**Issue by RobZenFL** [ArVdC/TimeManager#23]
Hi, I've used the plugins for a long time now, but had a 2 years break in having a minecraft server. Atm I'm building a new one and this was one of the first plugins I installed :D Thank you for your great work!
Now after some time building the server I realized I  got some problems in different worlds. The time cycle works good until a specific time, then the time freezes and stays there forever. Its always at 19:00 o'clock. First it only happened in one world, now it happens in several worlds. But only in worlds, where I slowed down the daytime (and perhaps one reason could be that the night is faster than the day, but I'm still trying to verify that). Do you have any idea, why this could happen?

git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
TimeManager 1.7.2 (but it also happens in 1.8.0)

Config file: https://pastebin.com/54tzis1q

No errors in console as far as I can see. Thank you for your help!

**Comment by ArVdC** [comment]
I found the cause of the problem. Thank you for reporting it to me.
I need to do some testing before posting an update but it shouldn't take much time.

**Comment by ArVdC** [comment]
Please try the [v1.8.1 release](https://github.com/ArVdC/TimeManager/releases/tag/v1.8.1), I think it's solved.

**Comment by RobZenFL** [comment]
I had a first look and it seems as its solved, yes. I'll have a deeper look later the day and test different values. Thank you for your fast work :)

**Comment by RobZenFL** [comment]
I now checked two worlds, where the problems began and changed the values a bit. Seems like everything is working just fine now. Thank you!

**Comment by ArVdC** [comment]
Good, thank you again for helping me find the bugs and being able to correct them.
And a little in advance: Happy New Year !
