### ISSUE TITLE
Sleeping speeds up time

### ISSUE THREAD

**Issue by Mark-A-Richardson** [ArVdC/TimeManager#24]
Minecraft Paper v1.20.4:381
TimeManager v1.8.1

I just updated our Minecraft server to version 1.20.4.  We have the Speed set to 0.5 (So the day and night would last twice as long). 
 Whenever someone sleeps (skipping the night), the speed of time seems to increase by a certain amount.  After a few nights of sleeping the days were lasting less than a minute.
 
Tested leaving it for a couple of in-game days without sleeping, and the speed of time did not seem to increase, indicating the sleeping skipping time process was the thing increasing the speed. 
 
Also tested setting the Speed back to 1.0, and as far as I could tell, time did not speed up after sleeping. 

I've attached my config file, if it helps. (Renamed to .txt so I can upload)
[config.txt](https://github.com/ArVdC/TimeManager/files/13864472/config.txt)

**Comment by ArVdC** [comment]
You are absolutely right.
Apparently a new speed modifier is superimposed on the previous one every time someone sleeps through the night.
Thank you for letting me know. I will try to find the cause.

**Comment by ArVdC** [comment]
I think I found where the error was. This should be resolved.
Please try [version 1.8.2](https://github.com/ArVdC/TimeManager/releases/tag/v.1.8.2) before closing this issue.
Thanks

**Comment by Mark-A-Richardson** [comment]
I've been running with the new version for a couple of hours now, and haven't seen any issues.  So I would say it's fixed.
Thank you for the quick turnaround.
