### ISSUE TITLE
Error message while resetting a world

### ISSUE THREAD

**Issue by RobZenFL** [ArVdC/TimeManager#25]
Hey, while our resource world was automatically reset, an error message from TimeManager appeared. I don't think it's breaking something, but I just wanted to let you know.
(Reset means the world is deleted and created again with the same name, so after that operation TM has the same settings for the "same" world - that works just fine)

Error message: https://pastebin.com/BHXxb1DS
Full log of the reset: https://pastebin.com/ahQX3q7y

Server version: git-Paper-447 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0052e2d)
TimeManager version: 1.8.2

**Comment by ArVdC** [comment]
How do you go about resetting the world ? What command do you use to do this ?

**Comment by RobZenFL** [comment]
We use a plugin for it: [Link](https://www.spigotmc.org/resources/xenoworldreset-%E2%9C%A8-optimized-seamless-scheduled-world-resetting%E3%80%8C1-13-1-20%E3%80%8D-25-sale.99431/)

I think the free version of the plugin uses the same method, the above is a paid resource: [Link](https://www.spigotmc.org/resources/cyberworldreset-%E2%9A%A1-regenerate-worlds-at-a-scheduled-time%E3%80%8C1-8-1-20%E3%80%8D.96834/)

**Comment by ArVdC** [comment]
I found out what was wrong. During the reset, the world obviously became temporarily inaccessible, and the scheduler blocked the first time the error was encountered.
This will be fixed in the next update.
Thank you for reporting it to me.

**Comment by ArVdC** [comment]
Here we are : [https://github.com/ArVdC/TimeManager/releases/tag/v1.9.0](https://github.com/ArVdC/TimeManager/releases/tag/v1.9.0)

**Comment by RobZenFL** [comment]
You are awesome, thank you very much!
