### ISSUE TITLE
config.yml resets on server restart

### ISSUE THREAD

**Issue by Collin146** [ArVdC/TimeManager#26]
Hello, I've been trying to get the plugin to run on my PaperMC server, on 1.20.1 though every time I make an edit to the config.yml to for example, slow down daytime, the file gets reset every time the server starts. Not quite sure why this is happening?

**Comment by Collin146** [comment]
Was only actually able to slow down daytime by using the `/tm set speedDay 0.5` command. When I edit the config.yml directly through a text editor, the values reset on restart. Might be an issue on my part due to editing the file whilst the server is running. though Will double-check since I see that can cause issues too.

**Comment by ArVdC** [comment]
If you make changes to the config file while the server is running, then use the `/tm reload config` command to commit your changes.
