### ISSUE TITLE
cmds.yml quotes bug

### ISSUE THREAD

**Issue by sorandno** [ArVdC/TimeManager#28]
cmdsList:
  '1':
    cmds:
      '1': /shigenreset
    cmdsRefTime: UTC+9
    plholderRefWorld: world
    time: '11:59'
    date: '2024-06-01'
    repeatFreq: month

Command is not executed.

time: It seems that it does not work if the time specification is set to 10:00 or more.

repeatFreq: May only be month.

**Comment by ArVdC** [comment]
I tried to reproduce the error, without success. Perhaps there is another element that could be the cause of the malfunction ?

`version: 1.9.0`
`useCmds: 'true'`
`cmdsList:`
 ` '1':`
`    cmds:`
`      '1': /say Hello world !`
`    cmdsRefTime: UTC+9`
`    plholderRefWorld: World01`
`    time: '22:40'`
`    date: '2024-06-05'`
`    repeatFreq: month`

-> `[22:40:00 INFO]: [Server] Hello world !`

**Comment by sorandno** [comment]
time: 22:40
In my environment, if it is 10:00 or more, it will be converted between single quotes.
And if it's after 10:00, it may change to a different time.
time: '10:00'

Isn't it because it's sandwiched between single quotes?

**Comment by sorandno** [comment]
It may not work if it is enclosed in single quotes.


    time: '20:00'
    repeatFreq: day
This is working fine.

**Comment by sorandno** [comment]
time: '11:59'
    repeatFreq: month
    
    This is not working.

**Comment by ArVdC** [comment]
You're right, something is wrong with the `time` values ​​but I haven't found what yet.
Single quotes allow values ​​containing `:` to be read correctly. I therefore think it is important to use them.

**Comment by sorandno** [comment]
There are times when using single quotes doesn't work properly in my case.
I believe there is a bug because there are times when it works fine.

**Comment by sorandno** [comment]
I don't know if it's a bug that only exists in the month setting, but I hope they find the cause.

**Comment by sorandno** [comment]
If it doesn't work, it may have been converted to a different time.

**Comment by ArVdC** [comment]
Please try this patch, it will probably fix this issue : [v1.9.1-b](https://github.com/ArVdC/TimeManager/releases/tag/v1.9.1-b)

**Comment by sorandno** [comment]
thank you
i will try!

**Comment by sorandno** [comment]
It worked normally when double quotes were added.
'09:38'→'9:38'

If you don't put double quotes, it was converted to another time.
09:39→04:00

Use with double quotes.
Thank you for your response.

**Comment by sorandno** [comment]
Ah... it's a single quote.

**Comment by ArVdC** [comment]
Does the 'month' frequency still pose any problem?

**Comment by sorandno** [comment]
The one at '9:38' above worked with the month setting, so I don't think there is a problem.
