### ISSUE TITLE
Question - Time day cycles

### ISSUE THREAD

**Issue by Pro245Mc** [ArVdC/TimeManager#30]
Hi, 
Love this powerful plugin, been using it for a year and I ready need to write you a good review.
I wanted to know If it's possible to have command launch in 7 day cycle?

Example:
After "1 minecraft day" has passed by launching a command, on the  2nd day, a second command can me launched on the next  day. And this cycles around a seven day period. This would be amazing as commands can be looped through the week.
Maybe it already exists?

Also, I'm not sure if i'm doing something wrong but in my conf, time manager will launch commands for all the  worlds even if the conf if configured for it not to.

Is this a bug, or me.

Thanks you so much. 

...................................................conf.yml

version: 1.9.0
refreshRate: 2
wakeUpTick: 0
newDayAt: 06:00
worldsList:
  world:
    start: 0
    daySpeed: 0.33
    nightSpeed: 0.33
    sleep: 'true'
    sync: 'false'
    firstStartTime: default
  world_nether:
    start: 0
    daySpeed: 0.33
    nightSpeed: 0.33
    sleep: 'true'
    sync: 'false'
    firstStartTime: default
  world_the_end:
    start: 0
    daySpeed: 0.33
    nightSpeed: 0.33
    sleep: 'true'
    sync: 'false'
    firstStartTime: default
  world_exploration:
    start: 0
    daySpeed: 0.33
    nightSpeed: 0.33
    sleep: 'true'
    sync: 'false'
    firstStartTime: default
  world_area_51:
    start: 0
    daySpeed: 0.33
    nightSpeed: 0.33
    sleep: 'true'
    sync: 'false'
    firstStartTime: default
    
    ..............................................cmd.yml
version: 1.9.0
useCmds: 'true'
cmdsList:
  gardom_global_sunrise_music:
    cmds:
      '1': /mycommand
    cmdsRefTime: world_exploration
    plholderRefWorld: world_exploration
    time: 05:00
    date: '0001-01-01'
    repeatFreq: day

**Comment by Pro245Mc** [comment]
i figured it out. elapsed time setting :) Thanks and you will get your review soon. :) Great plugin !

**Comment by ArVdC** [comment]
For a command to execute in a specific world, use the name of the world as an argument (if the command allows it).
For the repeat every week, I can consider a solution for the next update, but I can't promise it will be soon.

**Comment by Pro245Mc** [comment]
Thanks, sound great. I kind of cheated by resetting the elapsed days to reset the dates, but it would be amazing to have the feature. Thanks for the tips

**Comment by Pro245Mc** [comment]
Hi, just wanted to know if the  {tm_yearday} you added yesterday was to be able to do the weekly cycles? and if yes, can you give a breef explanation please? Thanks so much

**Comment by ArVdC** [comment]
No, it's just a new placeholder giving  the number of the day in the year (from 1 to 365).
I'm still working on the weekly repetition.

**Comment by ArVdC** [comment]
I think it works, please give me your feedback : [v1.9.1-b3](https://github.com/ArVdC/TimeManager/releases/tag/v1.9.1-b3)
