### ISSUE TITLE
Plugin Resetting

### ISSUE THREAD

**Issue by Supersmurf82** [ArVdC/TimeManager#34]
I downloaded the latest version of the plugin and tried to configure it to run with mvdwplaceholderapi , as well as changing the language from default to en_US. Every time I restart the server, the plugin resets itself to startup configurations, removing all the changes I've made. I attempted multiple different settings after this, like changing to placeholderapi or downgrading plugin versions, yet still no sign of functionality. This issue didn't present itself though a couple of months ago, as it worked fine without issues. 

On every server I had that used this plugin, they all ran on Pufferfish 1.20.4 (Paper Fork).

**Comment by ArVdC** [comment]
Have you tried editing the file when the server is down?
On some occasions the yaml file is modified and saved by the plugin, which can cause a reset of the changes.
