### ISSUE TITLE
Exploding log /now

### ISSUE THREAD

**Issue by ChrissW-R1** [ArVdC/TimeManager#36]
My server log will be flooded with the following logging entry:

`[Server thread/WARN]: [TimeManager] Only players can use the '/now' command. Try to use '/tm now' instead.`

We using the latest version 1.9.1.

**Comment by ArVdC** [comment]
Maybe someone used "/now" in a commandblock with a clock ?
This server message only appears if an entity that is not a player uses the command.

**Comment by ChrissW-R1** [comment]
You're right. Sorry, there is an very old map on our server, which if I unload, the messages will stop.
Thanks for the hint. Now I've to find the abandoned command block.
