### ISSUE TITLE
Sleep does not work with a fixed time world.

### ISSUE THREAD

**Issue by fenneltheloon** [ArVdC/TimeManager#4]
If I sleep in a world with normal time, the time in other worlds is displaced by the same amount as well. 
(I have a world with normal time and one that is set to noon forever. When I sleep in the first world, the second is suddenly night.)
Can I have it so sleeping in one world does not affect time in any way in another world?

**Comment by ArVdC** [comment]
Hi, this is not normal at all.
Which server version are you using?
