### ISSUE TITLE
When setting different daySpeed and nightSpeed the day freezes at 7p.m.

### ISSUE THREAD

**Issue by piojanu** [ArVdC/TimeManager#6]
Hi!

Thanks for the plugin, it is very useful. However, we would like to set our day longer than the night. And it won't work. We've tested setting the daySpeed for different values (i.e. 0.1, 0.2, 0.5, 0.9) while leaving the nightSpeed to 1.0, and in such case, the day freezes. Most often, it stops at 7:00 pm and won't progress into the night.

Thanks for your support,
Piotr

**Comment by Mordeus** [comment]
I have the same issue, as long as its 1.0 for day it works, I have mine set to 1.0 for day and 2.0 for night and it works, I want it to be .5 for day though, when its set to that, or anything below 1.0 it freezes at 19:00

**Comment by ArVdC** [comment]
Hi,
Thanks for the bug description.
I will check this ASAP, but it may take a while to fix it. I'll keep you informed.

**Comment by ArVdC** [comment]
Hi,
I forgot to update the doDaylightCycle gamerule when the timer goes from a decreased speed to a normal or accelerated speed. So it can unfortunately stop at 6:00 a.m. or 7:00 p.m.
I will post a fix shortly, maybe tonight or tomorrow.

**Comment by ArVdC** [comment]
Please try the [1.3.1 release](https://github.com/ArVdC/TimeManager/releases/tag/v1.3.1), it should solve the problem.
